# Generated by Django 3.0.5 on 2020-08-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='port',
            name='image',
            field=models.ImageField(blank=True, upload_to='portapp/images/'),
        ),
    ]
