# Generated by Django 3.0.5 on 2020-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_auto_20200824_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
