# Generated by Django 3.0.5 on 2020-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_port_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
