# Generated by Django 3.0.5 on 2020-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_auto_20200824_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='project',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
