# Generated by Django 3.0.5 on 2020-08-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0005_port_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='project',
        ),
    ]
