# Generated by Django 3.0.5 on 2020-10-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_portnew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortNew',
            new_name='NewPort',
        ),
    ]
