# Generated by Django 3.0.5 on 2020-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0009_auto_20201010_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
